### ISSUE TITLE
Human comments for Suricata eBPF code

### ISSUE THREAD

**Issue by sdsen** [eBPFDevSecTools/ebpf-projects-annotations#27] opened 2023-03-21 15:43 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by palanik1** [comment] 2023-04-03 04:37
closing as duplicate of #43

**Closed by palanik1** 2023-04-03 04:37 UTC
Labels: help wanted, HumanComments
