### ISSUE TITLE
Split annotations into separate dbs based on generator

### ISSUE THREAD

**Issue by palanik1** [eBPFDevSecTools/ebpf-projects-annotations#47] opened 2023-04-03 04:40 UTC
Currently all annotations are stored in a single annotated db. To support evolution in annotation fields, we would like to split annotations into separate dbs as follows
- [x] expert_annotated based on source code analysis
- [ ] human_annotated based on human comments
- [ ] AI annotated based on AI4Code model
- [ ] merged annotated that combines expert_annotated db with multiple human_annotated dbs and AI annotated dbs.

**Comment by sdsen** [comment] 2023-04-03 06:28
@palanik1 by design expert_annotated based on source code analysis is its own db right ? or do you need some mods for it?

**Comment by palanik1** [comment] 2023-04-03 07:41
@sdsen No mods needed at this point..

**Comment by sdsen** [comment] 2023-08-17 07:02
Will get addressed by https://github.com/eBPFDevSecTools/annotations-search-ui/issues/5 and https://github.com/eBPFDevSecTools/annotations-search-ui/issues/6. Closing.

**Closed by sdsen** 2023-08-17 07:02 UTC
Labels: Enhancement
